# Generated by Django 5.0.4 on 2024-06-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название на русском')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название на английском')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Название на узбекском')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
