# Generated by Django 5.0.4 on 2024-06-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(default=1, verbose_name='Описание на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(default=1, verbose_name='Описание на русском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description_uz',
            field=models.TextField(default=1, verbose_name='Описание на узбекском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=1, upload_to='categories/', verbose_name='Изображение (200x200)'),
            preserve_default=False,
        ),
    ]
