# Generated by Django 5.0.4 on 2024-06-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_description_en_category_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=100, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
