# Generated by Django 5.0.4 on 2024-06-14 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_collections',
            field=models.BooleanField(default=1, verbose_name='Есть коллекции'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название на русском')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название на английском')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Название на узбекском')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.collection', verbose_name='Коллекция'),
        ),
    ]
